<?php

namespace NTI\SyncBundle\Repository;

/**
 * SyncDeleteStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncDeleteStateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFromTimestamp($timestamp) {
        $qb = $this->createQueryBuilder('s');
        $qb ->andWhere('s.timestamp >= :timestamp')
            ->setParameter('timestamp', $timestamp)
            ->orderBy('s.timestamp', 'asc');
        return $qb->getQuery()->getResult();
    }
}
