<?php

namespace NTI\SyncBundle\Repository;

/**
 * SyncMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
